version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d social_api"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/social_api?sslmode=disable
      PORT: 8080
      JWT_SECRET: jwt_secret_key
      REFRESH_TOKEN_SECRET: refresh_token_secret_key
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["go", "run", "cmd/api/main.go"]

volumes:
  postgres_data: