version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/social_api?sslmode=disable
      PORT: 8080
      JWT_SECRET: jwt_secret_key
      REFRESH_TOKEN_SECRET: refresh_token_secret_key
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: